### ISSUE TITLE
reboot hosts handler occurs without changes

### ISSUE THREAD

**Issue by xunholy** [raspbernetes/k8s-cluster-installation#57]
# Details

The hosts should only need to be reboot for significant changes that require them to be restarted.

Currently, without any changes they'll still trigger into a host reboot which isn't intended.

**Comment by xunholy** [comment]
After doing several trials what seems to be the offending `notify` that triggers the host reboot handler is the following task:

```
- name: install log2ram
  command: /bin/sh ./install.sh
  args:
    chdir: '/opt/log2ram'
  register: log2ram
  changed_when: '"Reboot to activate log2ram" in log2ram.stdout'
  notify: reboot hosts
```
